# Generated by Django 6.0.3 on 2026-09-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel_app', '0009_college_groups_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
