# Generated by Django 6.0.3 on 2026-09-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel_app', '0010_group_archived_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.AlterField(
                model_name='studentprofile',
                name='parent_name',
                field=models.CharField(blank=True, max_length=100),
            )],
        ),
        migrations.CreateModel(
            name='ImportedGradeCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('source_class', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('source_column', models.CharField(max_length=64)),
                ('original_value', models.JSONField(blank=True, null=True)),
                ('original_header', models.JSONField(blank=True, null=True)),
                ('content_sha256', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabel_app.group')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabel_app.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabel_app.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_id', 'source_class', 'source_row', 'source_column'), name='unique_imported_grade_cell')],
            },
        ),
    ]
